version: '3'
services:
  web:
    command: > # 컨테이너 실행 시 마이그레이션 자동 실행 후, Django 서버 실행
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app # local에서의 변경사항을 컨테이너에 바로 반영되도록 마운트
    environment:
      - DEBUG=True # 개발 모드로 설정
    ports:
      - "8000:8000"